<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeStreamEntry</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCi8vZ2V0
IGNhY2hlIGhhbmRsZQpDYWNoZSBjYWNoZSA9IGdldENhY2hlKHBpcGVsaW5lQ3Vyc29yKTsKCk9i
amVjdCBjYWNoZUtleSA9IG51bGw7CmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgia2V5IikpCnsK
CS8vZ2V0IHRoZSBmaWxlbmFtZSBzdHJpbmcgb2JqZWN0IG91dCBvZiB0aGUgcGlwZWxpbmUKCWNh
Y2hlS2V5ID0gKFN0cmluZykgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsKfQoKYm9vbGVhbiBy
ZW1vdmVkID0gZmFsc2U7CnRyeSB7CglyZW1vdmVkID0gRWhjYWNoZUlPU3RyZWFtcy5yZW1vdmVT
dHJlYW1FbnRyeShjYWNoZSwgY2FjaGVLZXkpOwp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7Cgl0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQoKLy9vdXRwdXQgc2VjdGlvbgpwaXBlbGlu
ZUN1cnNvci5sYXN0KCk7CgovL291dHB1dCBkZWxldGVkIGZsYWcKSURhdGFVdGlsLnB1dChwaXBl
bGluZUN1cnNvciwgInJlbW92ZWQiLCBuZXcgQm9vbGVhbihyZW1vdmVkKS50b1N0cmluZygpLnRv
TG93ZXJDYXNlKCkpOwoKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
