<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFullStream</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgpib29sZWFuIHN1Y2Nl
c3MgPSBmYWxzZTsKaW50IHJlYWRMZW5ndGggPSAwOwp0cnkKewoJaWYgKGN1cnNvci5maXJzdCgi
aW5wdXRTdHJlYW0iKSkKCXsKCQlJbnB1dFN0cmVhbSBpbnB1dFN0cmVhbSA9IChJbnB1dFN0cmVh
bSkgY3Vyc29yLmdldFZhbHVlKCk7CgkJU3RyaW5nIGNoYXJzZXROYW1lID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjdXJzb3IsICJjaGFyc2V0TmFtZSIpOwoKCQkvLyBDcmVhdGUgYSBCdWZmZXJlZFJl
YWRlciBmcm9tIHRoZSBpbnB1dCBzdHJlYW0KCQlCdWZmZXJlZFJlYWRlciByZWFkZXIgPSBudWxs
OwoJCWlmIChjaGFyc2V0TmFtZSAhPSBudWxsKQoJCXsKCQkJcmVhZGVyID0gbmV3IEJ1ZmZlcmVk
UmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRlcihpbnB1dFN0cmVhbSwgY2hhcnNldE5hbWUpKTsK
CQl9CgkJZWxzZQoJCXsKCQkJcmVhZGVyID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0
cmVhbVJlYWRlcihpbnB1dFN0cmVhbSkpOwoJCX0KCgkJcmVhZExlbmd0aCA9IDA7CgkJd2hpbGUg
KHJlYWRlci5yZWFkKCkgPiAtMSl7CgkJCXJlYWRMZW5ndGgrKzsKCQl9CgkJCgkJc3VjY2VzcyA9
IHRydWU7Cgl9Cn0KY2F0Y2ggKFVuc3VwcG9ydGVkRW5jb2RpbmdFeGNlcHRpb24gdXNlKQp7Cgl0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbih1c2UpOwp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7
Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQpmaW5hbGx5CnsJICAgIAoJLy9vdXRw
dXQgc2VjdGlvbgoJY3Vyc29yLmxhc3QoKTsKCQkJCgljdXJzb3IuaW5zZXJ0QWZ0ZXIoInN1Y2Nl
c3MiLCBuZXcgQm9vbGVhbihzdWNjZXNzKS50b1N0cmluZygpKTsKCWN1cnNvci5pbnNlcnRBZnRl
cigibGVuZ3RoIiwgbmV3IEludGVnZXIocmVhZExlbmd0aCkudG9TdHJpbmcoKSk7CgkKCWN1cnNv
ci5kZXN0cm95KCk7Cn0=</value>
</Values>
